
import React, { useState } from 'react';
import { Equipment, MaintenancePrediction, Task } from '../types';
import { predictEquipmentFailure } from '../services/geminiService';
import { 
  Activity, Thermometer, Gauge, Zap, AlertTriangle, CheckCircle, 
  Settings, Wrench, Calendar, BrainCircuit, Loader2, RefreshCcw, FileText,
  CheckCircle2, ArrowRight
} from 'lucide-react';
import { 
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area 
} from 'recharts';
import { useUser } from '../contexts/UserContext';

// Mock Data Generator for chart visualization
const generateMockHistory = (baseTemp: number, baseVib: number) => {
  return Array.from({ length: 15 }, (_, i) => ({
    time: `${8 + i}:00`,
    temp: baseTemp + Math.random() * 5 - 2,
    vib: baseVib + Math.random() * 0.5 - 0.2,
  }));
};

const PredictiveMaintenanceModule: React.FC = () => {
  const { currentUser, equipment, updateEquipment } = useUser();
  const [selectedEquipment, setSelectedEquipment] = useState<Equipment | null>(null);
  const [loading, setLoading] = useState(false);
  const [mockChartData, setMockChartData] = useState<any[]>([]);
  const [scheduleStatus, setScheduleStatus] = useState<'idle' | 'success'>('idle');

  // Permissions check
  const canAccess = ['ADMIN', 'Site_HSE_Manager', 'Regional_HSE_Director', 'Head_Group_HSE', 'Site_Supervisor', 'Maintenance_Lead'].includes(currentUser.role);

  if (!canAccess) {
    return (
      <div className="flex flex-col items-center justify-center h-[calc(100vh-200px)] text-center p-12 animate-in fade-in">
        <div className="bg-slate-50 p-8 rounded-full mb-6">
            <AlertTriangle size={48} className="text-orange-400" />
        </div>
        <h3 className="text-2xl font-black text-slate-800 uppercase tracking-tight">Restricted Access</h3>
        <p className="text-slate-500 font-medium max-w-xs mt-2">This module requires Maintenance or HSE Management clearance.</p>
      </div>
    );
  }

  const handleSelectEquipment = (eq: Equipment) => {
    setSelectedEquipment(eq);
    setScheduleStatus('idle');
    // Generate fresh mock history based on current sensor readings for visualization
    setMockChartData(generateMockHistory(eq.sensors.temperature, eq.sensors.vibration));
  };

  const handleRunAnalysis = async () => {
    if (!selectedEquipment) return;
    setLoading(true);
    setScheduleStatus('idle');
    try {
      const prediction = await predictEquipmentFailure(selectedEquipment);
      
      const updatedEquipment = { ...selectedEquipment, prediction };
      
      // Update global state via context
      updateEquipment(updatedEquipment);
      setSelectedEquipment(updatedEquipment);
      
    } catch (err) {
      alert("Failed to generate predictive analysis.");
    } finally {
      setLoading(false);
    }
  };

  const handleScheduleMaintenance = () => {
      if (!selectedEquipment || !selectedEquipment.prediction) return;

      const savedTasks = localStorage.getItem('hse_tasks');
      const currentTasks: Task[] = savedTasks ? JSON.parse(savedTasks) : [];

      const newTask: Task = {
          id: `T-MAINT-${Date.now()}`,
          title: `Prev. Maint: ${selectedEquipment.name}`,
          description: `AI DETECTED RISK: ${selectedEquipment.prediction.rootCauseSuspect}. \nRECOMMENDATION: ${selectedEquipment.prediction.recommendedAction}. \n\nGenerated by Predictive Maintenance Module.`,
          assignee: currentUser.id, // Auto-assign to current user for demo
          priority: selectedEquipment.prediction.failureProbability > 60 ? 'High' : 'Medium',
          category: 'Maintenance',
          status: 'ToDo',
          dueDate: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0], // Default 3 days out
          createdAt: new Date().toISOString(),
          createdBy: 'AI System'
      };

      const updatedTasks = [newTask, ...currentTasks];
      localStorage.setItem('hse_tasks', JSON.stringify(updatedTasks));
      setScheduleStatus('success');
      
      // Reset success state after delay
      setTimeout(() => setScheduleStatus('idle'), 3000);
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 animate-in slide-in-from-bottom-4 duration-500 pb-20">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-slate-200 pb-6">
        <div className="flex items-center space-x-5">
          <div className="bg-indigo-600 p-5 rounded-[2rem] text-white shadow-2xl shadow-indigo-500/20">
            <Activity size={32} />
          </div>
          <div>
            <h2 className="text-4xl font-black text-slate-800 tracking-tighter uppercase leading-none">Predictive Maint.</h2>
            <p className="text-slate-400 text-xs font-bold uppercase tracking-widest mt-2 border-l-2 border-indigo-500 pl-4">AI-Driven Asset Reliability</p>
          </div>
        </div>
        <div className="flex gap-4">
           <div className="bg-white border border-slate-200 px-5 py-2.5 rounded-2xl flex items-center gap-3 shadow-sm">
              <span className="text-[10px] text-slate-400 font-black uppercase tracking-widest">System Status</span>
              <p className="text-emerald-600 font-black text-xs flex items-center gap-1 uppercase tracking-wider"><Zap size={14}/> Online</p>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 h-[calc(100vh-240px)] min-h-[600px]">
        
        {/* Left: Equipment List */}
        <div className="lg:col-span-4 flex flex-col bg-white rounded-[2.5rem] shadow-xl border border-slate-100 overflow-hidden">
            <div className="p-6 border-b border-slate-100 bg-slate-50/50">
                <h3 className="text-lg font-black text-slate-800 uppercase tracking-tight">Monitored Assets</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mt-1">{equipment.length} Connected Units</p>
            </div>
            <div className="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar">
                {equipment.map(eq => (
                    <div 
                        key={eq.id}
                        onClick={() => handleSelectEquipment(eq)}
                        className={`p-5 rounded-[2rem] border-2 transition-all cursor-pointer hover:shadow-lg group relative overflow-hidden ${
                            selectedEquipment?.id === eq.id 
                                ? 'border-indigo-600 bg-indigo-50/10' 
                                : 'border-slate-50 bg-white hover:border-slate-200'
                        }`}
                    >
                        <div className={`absolute top-0 left-0 w-1.5 h-full transition-colors ${
                            eq.status === 'Critical' ? 'bg-red-500' :
                            eq.status === 'Warning' ? 'bg-orange-500' :
                            eq.status === 'Maintenance' ? 'bg-blue-500' :
                            'bg-emerald-500'
                        }`}></div>
                        
                        <div className="pl-4">
                            <div className="flex justify-between items-start mb-2">
                                <div>
                                    <h4 className={`font-black text-sm uppercase tracking-tight ${selectedEquipment?.id === eq.id ? 'text-indigo-900' : 'text-slate-800'}`}>{eq.name}</h4>
                                    <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mt-0.5">{eq.type} • {eq.location}</p>
                                </div>
                                {eq.prediction && (
                                    <div className="bg-indigo-600 text-white p-1.5 rounded-full shadow-lg shadow-indigo-500/30">
                                        <BrainCircuit size={12} />
                                    </div>
                                )}
                            </div>
                            
                            <div className="grid grid-cols-2 gap-3 mt-3">
                                <div className="bg-slate-50 p-2 rounded-xl border border-slate-100">
                                    <p className="text-[9px] text-slate-400 font-black uppercase flex items-center gap-1"><Thermometer size={10}/> Temp</p>
                                    <p className={`text-xs font-bold ${eq.sensors.temperature > 80 ? 'text-red-600' : 'text-slate-700'}`}>
                                        {eq.sensors.temperature}°C
                                    </p>
                                </div>
                                <div className="bg-slate-50 p-2 rounded-xl border border-slate-100">
                                    <p className="text-[9px] text-slate-400 font-black uppercase flex items-center gap-1"><Activity size={10}/> Vib</p>
                                    <p className={`text-xs font-bold ${eq.sensors.vibration > 5 ? 'text-red-600' : 'text-slate-700'}`}>
                                        {eq.sensors.vibration} mm/s
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>

        {/* Right: Detailed View */}
        <div className="lg:col-span-8 h-full">
            {selectedEquipment ? (
                <div className="bg-white rounded-[2.5rem] shadow-xl border border-slate-100 h-full flex flex-col overflow-hidden relative">
                    {/* Detail Header */}
                    <div className="p-8 border-b border-slate-100 flex flex-col md:flex-row justify-between items-start md:items-center bg-slate-50/30 gap-6">
                        <div>
                            <div className="flex items-center gap-3 mb-1">
                                <h3 className="text-2xl font-black text-slate-800 uppercase tracking-tighter">
                                    {selectedEquipment.name}
                                </h3>
                                <span className={`text-[9px] font-black px-3 py-1 rounded-lg border uppercase tracking-widest ${
                                    selectedEquipment.status === 'Operational' ? 'bg-emerald-50 text-emerald-700 border-emerald-100' :
                                    selectedEquipment.status === 'Critical' ? 'bg-red-50 text-red-700 border-red-100' :
                                    'bg-orange-50 text-orange-700 border-orange-100'
                                }`}>{selectedEquipment.status}</span>
                            </div>
                            <p className="text-xs font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
                                ID: {selectedEquipment.id} <span className="w-1 h-1 bg-slate-300 rounded-full"></span> Last Service: {selectedEquipment.lastMaintenanceDate} <span className="w-1 h-1 bg-slate-300 rounded-full"></span> {selectedEquipment.operationalHours} hrs
                            </p>
                        </div>
                        <button 
                            onClick={handleRunAnalysis}
                            disabled={loading}
                            className="bg-slate-900 hover:bg-slate-800 text-white px-6 py-3 rounded-2xl font-black uppercase text-[10px] tracking-widest flex items-center gap-2 transition-all shadow-xl active:scale-95 disabled:opacity-50"
                        >
                            {loading ? <Loader2 className="animate-spin" size={16} /> : <BrainCircuit size={16} />}
                            Run AI Diagnostics
                        </button>
                    </div>

                    <div className="flex-1 overflow-y-auto p-8 space-y-8 custom-scrollbar">
                        
                        {/* Live Telemetry Charts */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                            <div className="bg-white border border-slate-100 rounded-[2rem] p-6 shadow-lg">
                                <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-6 flex items-center gap-2">
                                    <Thermometer size={16} className="text-orange-500" /> Temperature Trend
                                </h4>
                                <div className="h-48">
                                    <ResponsiveContainer width="100%" height="100%">
                                        <AreaChart data={mockChartData}>
                                            <defs>
                                                <linearGradient id="colorTemp" x1="0" y1="0" x2="0" y2="1">
                                                    <stop offset="5%" stopColor="#f97316" stopOpacity={0.1}/>
                                                    <stop offset="95%" stopColor="#f97316" stopOpacity={0}/>
                                                </linearGradient>
                                            </defs>
                                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9"/>
                                            <XAxis dataKey="time" hide />
                                            <YAxis domain={['auto', 'auto']} width={30} tick={{fontSize: 10, fill: '#94a3b8', fontWeight: 'bold'}} axisLine={false} tickLine={false} />
                                            <Tooltip contentStyle={{borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)'}} />
                                            <Area type="monotone" dataKey="temp" stroke="#f97316" strokeWidth={3} fillOpacity={1} fill="url(#colorTemp)" />
                                        </AreaChart>
                                    </ResponsiveContainer>
                                </div>
                            </div>
                             <div className="bg-white border border-slate-100 rounded-[2rem] p-6 shadow-lg">
                                <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-6 flex items-center gap-2">
                                    <Activity size={16} className="text-blue-500" /> Vibration Analysis
                                </h4>
                                <div className="h-48">
                                    <ResponsiveContainer width="100%" height="100%">
                                        <LineChart data={mockChartData}>
                                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9"/>
                                            <XAxis dataKey="time" hide />
                                            <YAxis domain={['auto', 'auto']} width={30} tick={{fontSize: 10, fill: '#94a3b8', fontWeight: 'bold'}} axisLine={false} tickLine={false} />
                                            <Tooltip contentStyle={{borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)'}} />
                                            <Line type="monotone" dataKey="vib" stroke="#3b82f6" strokeWidth={3} dot={false} />
                                        </LineChart>
                                    </ResponsiveContainer>
                                </div>
                            </div>
                        </div>

                        {/* Incident History Context for AI */}
                        {selectedEquipment.relatedIncidents && selectedEquipment.relatedIncidents.length > 0 && (
                             <div className="bg-orange-50 border border-orange-100 rounded-3xl p-6">
                                <h4 className="text-xs font-black text-orange-800 uppercase tracking-widest mb-3 flex items-center gap-2">
                                    <FileText size={16} /> Related Incident History
                                </h4>
                                <ul className="space-y-2">
                                    {selectedEquipment.relatedIncidents.map((inc, i) => (
                                        <li key={i} className="flex items-center gap-2 text-xs font-bold text-orange-700">
                                            <div className="w-1.5 h-1.5 rounded-full bg-orange-400"></div>
                                            {inc}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {/* AI Prediction Results */}
                        {selectedEquipment.prediction ? (
                            <div className="bg-slate-900 text-white rounded-[2.5rem] p-8 relative overflow-hidden animate-in fade-in slide-in-from-bottom-2 shadow-2xl">
                                <div className="absolute top-0 right-0 p-8 opacity-10">
                                    <BrainCircuit size={180} />
                                </div>
                                
                                <div className="relative z-10">
                                    <div className="flex justify-between items-start mb-8 border-b border-white/10 pb-6">
                                        <div>
                                            <p className="text-indigo-400 text-[10px] font-black uppercase tracking-[0.2em] mb-1">AI Predictive Model</p>
                                            <h3 className="text-3xl font-black uppercase tracking-tighter">Maintenance Analysis</h3>
                                        </div>
                                        <div className="text-right">
                                            <p className="text-slate-400 text-[10px] font-black uppercase tracking-widest">Failure Probability</p>
                                            <p className={`text-5xl font-black tracking-tighter ${
                                                selectedEquipment.prediction.failureProbability > 70 ? 'text-red-400' : 
                                                selectedEquipment.prediction.failureProbability > 40 ? 'text-orange-400' : 'text-emerald-400'
                                            }`}>
                                                {selectedEquipment.prediction.failureProbability}%
                                            </p>
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                        <div className="bg-white/5 p-6 rounded-3xl border border-white/5 backdrop-blur-md">
                                            <div className="flex items-center gap-2 mb-3 text-indigo-300">
                                                <Calendar size={18} />
                                                <span className="text-[10px] font-black uppercase tracking-widest">Predicted Failure</span>
                                            </div>
                                            <p className="font-bold text-lg leading-tight">{selectedEquipment.prediction.predictedFailureDate}</p>
                                        </div>
                                        <div className="bg-white/5 p-6 rounded-3xl border border-white/5 backdrop-blur-md">
                                            <div className="flex items-center gap-2 mb-3 text-orange-300">
                                                <AlertTriangle size={18} />
                                                <span className="text-[10px] font-black uppercase tracking-widest">Root Cause Suspect</span>
                                            </div>
                                            <p className="font-bold text-lg leading-tight">{selectedEquipment.prediction.rootCauseSuspect}</p>
                                        </div>
                                        <div className="bg-white/5 p-6 rounded-3xl border border-white/5 backdrop-blur-md">
                                            <div className="flex items-center gap-2 mb-3 text-emerald-300">
                                                <Wrench size={18} />
                                                <span className="text-[10px] font-black uppercase tracking-widest">Recommendation</span>
                                            </div>
                                            <p className="font-bold text-lg leading-tight">{selectedEquipment.prediction.recommendedAction}</p>
                                        </div>
                                    </div>

                                    <div className="flex flex-col md:flex-row items-center gap-4 bg-indigo-600/20 p-5 rounded-[2rem] border border-indigo-500/30">
                                        <div className="p-3 bg-indigo-500/20 rounded-2xl text-indigo-300">
                                            <Calendar size={24} />
                                        </div>
                                        <div className="flex-1">
                                            <p className="text-[10px] text-indigo-300 font-black uppercase tracking-widest">Suggested Schedule</p>
                                            <p className="font-medium text-sm text-indigo-100">Schedule preventive maintenance by <span className="text-white font-bold border-b border-indigo-400">{selectedEquipment.prediction.maintenanceSchedule}</span></p>
                                        </div>
                                        <button 
                                            onClick={handleScheduleMaintenance}
                                            disabled={scheduleStatus === 'success'}
                                            className={`px-8 py-4 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all shadow-lg flex items-center gap-2 ${
                                                scheduleStatus === 'success' 
                                                ? 'bg-emerald-500 text-white cursor-default' 
                                                : 'bg-white text-slate-900 hover:bg-indigo-50 active:scale-95'
                                            }`}
                                        >
                                            {scheduleStatus === 'success' ? (
                                                <>
                                                    <CheckCircle2 size={16} /> Work Order Created
                                                </>
                                            ) : (
                                                <>
                                                    Create Work Order <ArrowRight size={14} />
                                                </>
                                            )}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        ) : (
                            <div className="bg-slate-50 border-2 border-slate-100 border-dashed rounded-[3rem] p-12 text-center h-[400px] flex flex-col items-center justify-center">
                                <div className="bg-white p-6 rounded-full mb-6 shadow-sm">
                                    <Activity size={48} className="text-slate-300" />
                                </div>
                                <h3 className="text-xl font-black text-slate-700 uppercase tracking-tight">Ready for Diagnosis</h3>
                                <p className="text-slate-400 text-sm mt-2 max-w-sm font-medium mx-auto">Initiate AI analysis to detect potential failures based on sensor anomalies and historical patterns.</p>
                                <button onClick={handleRunAnalysis} className="text-indigo-600 font-bold text-xs uppercase tracking-widest hover:underline mt-6">
                                    Start Analysis Process
                                </button>
                            </div>
                        )}

                    </div>
                </div>
            ) : (
                <div className="bg-white border-2 border-slate-100 rounded-[2.5rem] h-full flex flex-col items-center justify-center text-slate-400 p-12 text-center shadow-inner">
                    <div className="bg-slate-50 p-8 rounded-full mb-6 animate-pulse">
                        <Settings size={64} className="opacity-20" />
                    </div>
                    <h3 className="text-2xl font-black text-slate-300 uppercase tracking-tighter">Asset Selection Required</h3>
                    <p className="max-w-sm mx-auto mt-4 text-sm font-bold uppercase tracking-widest opacity-60">Choose an asset from the fleet list to view real-time telemetry and predictive insights.</p>
                </div>
            )}
        </div>

      </div>
    </div>
  );
};

export default PredictiveMaintenanceModule;
